project:
  type: website

website:
  title: "IAFF 6502/6505 Communicating Data with Web Apps"
  description: "Homepage for Communicating Data with Web Apps"
  site-url: "https://rshiny-is.cool"
  repo-url: "https://github.com/eteitelbaum/gwu-shinyapps"
  repo-actions: [edit, issue]
  page-navigation: true
  image: "images/webapps-logo.png"
  open-graph:
    image: "images/webapps-logo.png"
    image-width: 400
    image-height: 200
  twitter-card: true
  favicon: "images/webapps-logo.png"
  reader-mode: true
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/). 👷🛠️"
    left: "&copy; Copyright 2024, [Emmanuel Teitelbaum](https://emmanuel.teitelbaum.com)"
    background: "#0d0887"
    foreground: "#f0f921"
  sidebar:
    background: "#0d0887"
    foreground: "#f0f921"
    logo: "images/webapps-logo.png"
    pinned: true
    align: center
    tools:
      - icon: mortarboard-fill
        href: https://blackboard.gwu.edu
        text: "Blackboard"
        aria-label: "Blackboard"
      - icon: github
        href: https://github.com
        text: "Github"
        aria-label: "Github"
      - icon: r-project # bootstrap-reboot
        href: https://posit.co/download/rstudio-desktop
        text: "RStudio Desktop"
        aria-label: "RStudio Desktop"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course Information"
        contents:
          #- href: course-description.qmd
          #  text: Description
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: instructor.qmd
            text: Instructor
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          # - href: faq.qmd
          #   text: FAQ
      - section: "Homework Assignments"
        contents:
          - href: assignments/coding-assignment-1.qmd
            text: "Assignment 1"
          - href: assignments/coding-assignment-2.qmd
            text: "Assignment 2"
      - section: "Project"
        contents:
          - href: project/project-assignment.qmd
            text: "Project Assignment"
          - href: project/project-datasets.qmd
            text: "Datasets"
      - section: "Course Modules"
        contents:
          - href: modules/module-1.1.qmd
            text: "Module 1.1"
          - href: modules/module-1.2.qmd
            text: "Module 1.2"
          - href: modules/module-1.3.qmd
            text: "Module 1.3"
          - href: modules/module-1.4.qmd
            text: "Module 1.4"
          - href: modules/module-1.5.qmd
            text: "Module 1.5"
          - href: modules/module-2.1.qmd
            text: "Module 2.1"
          - href: modules/module-2.2.qmd
            text: "Module 2.2"
          - href: modules/module-2.3.qmd
            text: "Module 2.3"
          - href: modules/module-2.4.qmd
            text: "Module 2.4"
          - href: modules/module-2.5.qmd
            text: "Module 2.5"
      - section: "Workshop Schedule"
        contents: 
          - href: weeks/workshop-day1.qmd
            text: "Workshop Day 1"
          - href: weeks/workshop-day2.qmd
            text: "Workshop Day 2"
format:
  html:
    theme:
      light: [cosmo, theme-light.css]
      dark: cyborg
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    link-external-newwindow: true
freeze: auto
editor: source

